language: node_js
node_js:
  - "6.6.0"
before_script:
  - npm i
  - node_modules/gulp/bin/gulp.js build
script:
  - node_modules/gulp/bin/gulp.js test
notifications:
  irc:
    channels:
      - "chat.freenode.net#vanilla-framework"
      - "chat.freenode.net#canonical-webteam"
    on_success: change
    on_failure: always
  webhooks:
    urls:
      - "https://webhooks.gitter.im/e/9898d67dfc1dd39f9cb2"
    on_success: change
